### ISSUE TITLE
Ignore empty newlines

### ISSUE THREAD

**Issue by silkfire** [cpmcgrath/codealignment#101]
@cpmcgrath 

I had some issues with the extension until I realized that it actually doesn't work if there are empty lines in between the lines that you're trying to align.

E.g. aligning this code with CA has zero effect:

```csharp
public string FirstName { get; set; }

public string Surname { get; set; }

public int Age { get; private set; }

private Address Address { get;  set; }
```

Would it be possible to add such an option or to make CA smarter as to ignoring empty lines?

**Comment by cpmcgrath** [comment]
This is by design. If you don't want to use the be automatic selection you can just select the lines you want to align

**Comment by silkfire** [comment]
Got it! Thanks for a fantastically useful extension :)
