### ISSUE TITLE
Not avaiable for vs 2022 Preview

### ISSUE THREAD

**Issue by maciey** [cpmcgrath/codealignment#106]
I miss that a lot in newest VS 2022
What to do to have it there ?

**Comment by theolivenbaum** [comment]
Same here, looking forward to have it for VS2022 :)

**Comment by cpmcgrath** [comment]
Hi Sorry for my silence on these issues, It's definitely coming, last few weeks I've just been figuring out how I wanted to approach it. Unfortunately VS2022 isn't completely straight forward - A Visual Studio 2022 extension can't support earlier versions of Visual Studio.

Luckily the code change itself is pretty basic, so now that I've figured out what I want to do I should be able to knock it over quite quickly. Unfortunately, I probably won't be pushing it to the marketplace until basically when 2022 gets released. I'll be able to provide a VSIX to download though

**Comment by cpmcgrath** [comment]
I decided to make a new issue for it so it could follow a standard format I'm using for my extensions. #108 is for VS2022 support, I've included a link to the VSIX file that you can install in the preview. Any feedback is of course welcome
