### ISSUE TITLE
Can support align by member in a struct?

### ISSUE THREAD

**Issue by yanyongcheng** [cpmcgrath/codealignment#109]
Hi,Chris
Can the extension supoort like this:
![Snipaste_2021-11-30_11-15-20](https://user-images.githubusercontent.com/29299375/143979609-0bb47aca-1127-46d8-88e3-85cf56e1355e.png)

**Comment by cpmcgrath** [comment]
Sorry for the delay,
If you're wanting the location of the * changed, that's not something an alignment tool should ever handle - maybe your code formatter can do that before performing alignments.

As for the rest of the alignment, I would probably just do it by two align by space. Align the first 5, then align everything with your caret after the columns of the space you want to ignore.

You could also write a regex to align by the last space, or the last space before a semicolon.
