### ISSUE TITLE
Add ability to specify where to add spaces (ability to right align).

### ISSUE THREAD

**Issue by cpmcgrath** [cpmcgrath/codealignment#27]
Not sure how useful this would be. Feedback welcome.

Alignment Regex's have the
(?<x>) Match Group.
This will not change, but the following enhancements should be made.
(?<x>) Match Group should have an alias (?<compare>)
compare is the preferred syntax as it's more descriptive.

A new matching group (?<insert>) which defines where the spaces should be inserted. If it doesn't exist it should then use compare/x then the start of the matching regex.

**Comment by buzain** [comment]
It will be useful in certain cases. This is more readable for me:

``` JSON
{
     "firstName" : "John",
      "lastName" : "Doe",
      "nickname" : "The Man",
   "nationality" : "US",
           "age" : 28
}
```

compared to this:

``` JSON
{
   "firstName"   : "John",
   "lastName"    : "Doe",
   "nickname"    : "The Man",
   "nationality" : "US",
   "age"         : 28
}
```
