### ISSUE TITLE
Use tabs instead of spaces to indent ( if the user chooses ).

### ISSUE THREAD

**Issue by Acecool** [cpmcgrath/codealignment#33]
Tabs should be used for aligning because 1 character vs 4/5 characters over 10s of thousands of lines will increase file-size. Using this plugin to 13961 lines won't allow me to use my save macro ( which converts 5 spaces to tab, 4 spaces to tab, 3 spaces to tab, 2 spaces to tab, and trim trailing white-space ) because of the spaces-spam... 

The file I'm editing is 690kb when using tabs as aligners. However, when using spaces as aligners from this plugin made the file size 1,731KB... Over 1.1mb of just SPACES which is stupid. Yes, stupid because there are more spaces in the document than content whereby if using tabs the content would still outweigh tab content by more than 2 times.

I don't see why the option doesn't exist, and why it was edited in 2012 to remove the option to use tabs if the user wants: https://github.com/cpmcgrath/codealignment/commit/f79b6c707858a9fe81b5d13b53ca358be9b5cfea

**Comment by cpmcgrath** [comment]
Hi Acecool,
In Code Alignment options (from align by string click the cog) you can tick "Use IDE tab settings for alignment" to enable tabs (if the IDE settings also says that the tab key inserts tabs not spaces)
Prior to the commit you mentioned if your IDE settings inserted tabs then you were forced to insert tabs in alignments. As spaces are better for alignments (see https://github.com/cpmcgrath/codealignment/wiki/Tabs-&-Alignment ) Issue #9 said that if your IDE has that setting on, you should still have the option to use spaces, and that should be the default.

As for your file size. I would still say the size increase is insignificant. In terms of storage a MB on a TB drive is nothing. For transport, if you really were concerned about size you'd use compression (which would barely make the file size different) or if it was code you could minify it.
