### ISSUE TITLE
Support multiple instances of the same character

### ISSUE THREAD

**Issue by AGlezB** [cpmcgrath/codealignment#41]
I'd like to format this:

``` c#
int[] Numbers = {
    1, 2, 3,
    4 , 5 , 6 ,
    7  ,  8  ,   9
}
```

like this:

``` c#
int[] Numbers = {
    1, 2, 3,
    4, 5, 6,
    7, 8, 9
}
```

So far the only way to do it is to move the caret and align again which become a hassle with a lot of columns. Regular expressions didn't seem to work.

Usage scenarios:
1. Array initializers
2. Server logs (ftp, http, etc.)
3. SQL statements with many columns (select, insert)
4. Working with CSV files

TextFX can handle all of them as long as Unicode is not involved but I've had it insert 4k spaces in some instances when parsing server logs.

**Comment by cpmcgrath** [comment]
Hi,
The way code alignment handles this is through Chained Alignments - https://github.com/cpmcgrath/codealignment/wiki/Chaining-Alignments

I've thought about other methods such as an option to keep aligning until you reach the end of a line, but I feel this takes away too much control from the user. Chained Alignments let you stop when you want, change what you align by, and see the result as it happens.

I think there was also an implicit request in your example to be able to remove spaces when aligning. Issue #12 is about this. It's not the easiest change, and I'm still not sure how such a feature should be exposed in the UI.

**Comment by AGlezB** [comment]
Thanks for the quick response.

Can you implement this and call it "Matrix Alignment"? Chaining sound good but I this case the only the separator needs defining. Just keep aligning until you run out of separators and as long as I have a get a matrix I don't care what sort of control I _could_ have had.

The #12 can go as "Trim extra spaces" and checked by default. Let the users decide if they want the extra spaces (I'm betting no).
