### ISSUE TITLE
Feature: Comment alignment

### ISSUE THREAD

**Issue by consideRatio** [cpmcgrath/codealignment#42]
I would love to see the ability to make this code...

```
int i = 4;     // another comment
int x = 7;        // some comment
int y = 5;                        // another comment
int myFatAssVarWithIrritatinglyLongName = 5; // a final comment
```

indented with an algorithm like:
1: find the longest line in selection
2: indent all code-comments to the next TAB position after the found longest line's endpoint

so the code above would similar to this instead:

```
int i = 4;                                      // another comment
int x = 7;                                      // some comment
int y = 5;                                      // another comment
int myFatAssVarWithIrritatinglyLongName = 5;    // a final comment
```

That would be very, very useful!

**Comment by consideRatio** [comment]
One could also make sure all vertically connected code shares the same grouping distance. This way one could run a "reformat all single line comments in the document".

Vertically connected definition: not separated by a blank line.

**Comment by cpmcgrath** [comment]
Other than the "to the next TAB position" can't this be achieved by aligning by // ?

**Comment by cpmcgrath** [comment]
As the "To the next TAB" would be handled in #24 I'm going to close this ticket.
