### ISSUE TITLE
Can't install your extension in new VS"15"Preview

### ISSUE THREAD

**Issue by jakubsuchybio** [cpmcgrath/codealignment#43]
Hi,
### Installed product versions
- Visual Studio: [15 Preview]
### Description

At build 2016 Microsoft released Visual Studio 15 Preview.
There are some extensions that work there, but some that are not even searchable in "Extensions and Updates". Yours is one of those that are not searchable and not installable.
### Steps to recreate
1. Install Visual Studio 15 Preview: https://www.visualstudio.com/en-us/downloads/visual-studio-next-downloads-vs.aspx (Visual Studio "15" Preview with new installer)
2. Open VS15Preview
3. Open Extensions and Updates
4. Click on Online in the menu
5. Search for Code Alignment
6. Your extension doesn't pop up
### Current behavior

Your extension is not searchable in new Visual Studio 15 Preview
### Expected behavior

Your extension should or could be also in VS15Preview :)

Btw, I created recently one analyzer and made it to be an extension and it works there fine:
https://github.com/jakubsuchybio/DebuggingUsingsInsertor-Analyzer
If you needed something to compare yours setup of extension with.
Regards.

**Comment by cpmcgrath** [comment]
Thanks. Visual Studio makes extensions have to explicitly specify the versions they work with. Unfortunately as far as I'm aware there's no way to force Visual Studio to install an extension if it's not on this list.

So hopefully it's just add VS2015 to the list. I'll do some basic testing first to make sure it works. Hopefully I'll have an update for this within a week.

**Comment by jakubsuchybio** [comment]
I thank you! :)

**Comment by cpmcgrath** [comment]
Please note: This does not work with the Lightweight install of Visual Studio 15. Seems microsoft made it lightweight by not distributing a bunch of files extensions rely on (At least extensions that maintain compatibility from 2010 on).

**Comment by jakubsuchybio** [comment]
I can confirm, that Lightweight setup with:
- Visual Studio core edition
- .NET desktop development

shows your extension fine and I already installed it.
Didn't try just with the first only installation.

**Comment by cpmcgrath** [comment]
Ah, that's good to know. My tests with the Lightweight editor was just the "Visual Studio core editor" so that must cause the problem.
