### ISSUE TITLE
Can't get to work

### ISSUE THREAD

**Issue by MgSam** [cpmcgrath/codealignment#49]
I can't get this plugin to work correctly in Visual Studio. I'm trying to align multiple lines with commas.

```
[foo, bar, baz]
[1,2,3]
```

Desired:

```
[foo, bar, baz]
[1  , 2  , 3]
```

The closest thing I've found is this [wiki page](https://github.com/cpmcgrath/codealignment/wiki/Align-by-Comma), but when I try that regex, it doesn't do anything but align the first commas on the lines I have highlighted. I want _all_ commas aligned. 

So I have a few issues:
- Can't align by commas successfully.
- I can't figure out how to invoke the custom CodeAlignment shortcuts in VS- they're not listed in keyboard shortcuts. I've been manually pasting in the commas regex to the align-by-string.
- Why is comma alignment listed on the wiki but not a default in the plugin? Seems like a pretty common use-case.

Thanks for any help.

**Comment by cpmcgrath** [comment]
Hi, 
To get the shortcuts working check out this wiki page - https://github.com/cpmcgrath/codealignment/wiki/Enabling-shortcuts-in-Visual-Studio

To align multiple commas you must use align from caret or alignment chaining. Check out https://github.com/cpmcgrath/codealignment/wiki/Chaining-Alignments

As for doing all the alignments in one operation I've mentioned why I don't like this method here - https://github.com/cpmcgrath/codealignment/issues/41

And as a standard shortcut, the plan for a while had been to reduce the number of standard shortcuts and instead provide an easy way of sharing and grabbing them. I haven't got around to this and am unlikely to soon, so I might end up adding align by comma as a standard.
