### ISSUE TITLE
Add some documentation for what languages are supported

### ISSUE THREAD

**Issue by ianfixes** [cpmcgrath/codealignment#58]
This may be a stupid question, but I'm having trouble figuring out what language(s) are supported by this project.  Is it language-agnostic?  A single line in the README would be awesome.

**Comment by cpmcgrath** [comment]
Hi,
Sorry about my delay responding. Code Alignment is completely language-agnostic.

I think I mention that somewhere, but unfortunately my documentation is all over the place. Cleaning up documentation has been on my to do list for a long time.
