### ISSUE TITLE
RegEx Not Working?

### ISSUE THREAD

**Issue by Enteleform** [cpmcgrath/codealignment#63]
I've tried using `Edit.AlignByString` with the RegEx option enabled, but haven't had any success. There aren't any RegEx examples on codealignment.com, so I tried a few syntax variations.

Here's an example that works in the aligner I use with Sublime Text:

```
	public List<string> MyList = new List<string>{"A", "B", "C"};
	public int MyInt = 1;
	public string MyString = "2";
```

Align By:
```((\w+) ([A-Za-z0-9_<>]+))|(=)```
		
```
	public List<string> MyList   = new List<string>{"A", "B", "C"};
	public int          MyInt    = 1;
	public string       MyString = "2";
```
&nbsp;
I also tried doing something simple like `\w+` or `(\w+)`, but didn't see any results.

&nbsp;
-----

> Visual Studio 2017 x64 15.5.2

**Comment by cpmcgrath** [comment]
Hi,
The align by regex isn't used like that. It still works on the principle of "Do a Single Alignment" There's a few tutorials on the wiki about it. This is the primary one - https://github.com/cpmcgrath/codealignment/wiki/Aligning-using-Regular-expressions
