### ISSUE TITLE
Stop working for VS2012 after V14

### ISSUE THREAD

**Issue by wilianwrech** [cpmcgrath/codealignment#66]
I updated Code Alignment to version 14 on Visual Studio 12 and it stop working, downgraded back to version 13.1 and it's ok. I don't think this is proposed to happen, since it's not listed in manjor changes on releases page.
Microsoft Visual Studio Professional 2012
Version 11.0.61219.00 Update 5

**Comment by cpmcgrath** [comment]
Sorry for the delay getting back to you.
Just checked out the diffs, seems that all the Visual Studio references were changed from v11 (2012) to v12 (2013) in a pull request.
I'm pretty sure this was done by mistake, I can't think of any reason this was needed, I should be able to get a version out soon which fixes this.
