### ISSUE TITLE
Ignoring Leading Space in 'Align by space'

### ISSUE THREAD

**Issue by JohannesMP** [cpmcgrath/codealignment#67]
In Visual Studio 2015, when I use 'Align by space' on the following code:

```cpp
struct demo
{
    int a;
    std::vector<int> b;
};
```

I would expect to indent as follows:

```cpp
struct demo
{
    int              a;
    std::vector<int> b;
};
```

However this does not happen, because it appears that the leading spaces count as matching the 'aligned by space' criteria.

If I left-align my lines with no indentation at all:

```cpp
struct demo
{
int a;
std::vector<int> b;
};
```

Then running 'Align by space' does align `a` and `b`, but without the desired indentation

```cpp
struct demo
{
int              a;
std::vector<int> b;
};
```

-------

Would it be possible to simply have a setting to indent by space, but ignore leading spaces?

**Comment by cpmcgrath** [comment]
Hi,
The Align by space works from your current caret column. For more details see https://github.com/cpmcgrath/codealignment/wiki/Align-by-space
