### ISSUE TITLE
websites are down/broken

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [cpmcgrath/codealignment#81]
The websites are down/broken. Is development on this project still active?

http://www.codealignment.com
http://www.cpmcgrath.com

![2019-01-23-broken-codealignment-website](https://user-images.githubusercontent.com/34172339/51643442-7dc2e680-1f3a-11e9-880a-8454c593fd7f.png)

![2019-01-23-broken-cpmcgrath-website](https://user-images.githubusercontent.com/34172339/51643449-81566d80-1f3a-11e9-9ab7-65d3fb38dfd1.png)

**Comment by cpmcgrath** [comment]
Hi,
Development is still active, I've recently switched hosts. The old website had a lot of out of date information that confused people, so I've opted to start fresh. I'll get them online soon, but the github page is the best place to get the latest information.

**Comment by haakoo** [comment]
It might be an idea to have a temporary page at http://www.codealignment.com/ that either redirects to Github or just have a link to Github.

**Comment by bgr** [comment]
Still offline.
