### ISSUE TITLE
Regex alignment on preceding characters

### ISSUE THREAD

**Issue by bruno-trindade** [cpmcgrath/codealignment#82]
Hello!  As a ruby developer, I find myself with hash declarations like this:
```ruby
{
  foo: 'this is a value',
  foobar: 'this is another one',
  foobarbaz: 'this is not a value.  just kidding, yes it is.'
}
```
Currently there's no way to align these using this plugin (in VS Code).  It would be nice if the Regex would recognize captures and use those for alignment, e.g.:
`\S+:(\s)\S+`
would result in:
```ruby
{
  foo:       'this is a value',
  foobar:    'this is another one',
  foobarbaz: 'this is not a value.  just kidding, yes it is.'
}
```
Does this sound like a reasonable feature?  I'm not that experienced with C# but I could try to submit a PR if this sounds like something you want to pursue.  Thanks!

**Comment by cpmcgrath** [comment]
Hi Bruno, 
There's a ticket for this in the codealignment-vscode repository - https://github.com/cpmcgrath/codealignment-vscode/issues/7

Align by regex exists in the Visual Studio/Notepad++ version (https://github.com/cpmcgrath/codealignment/wiki/Aligning-using-Regular-expressions), but regexes in Javascript have significant limitations to them. You can capture groups, but you can only get the value of the group, not the index of the group.

As for your particular example though, you could use align by space - https://github.com/cpmcgrath/codealignment/wiki/Align-by-space (forgive the broken images, I'm doing a clean slate redo of some of my hosting and there's a few things I forgot are referenced in the wiki)

**Comment by bruno-trindade** [comment]
Just what I needed, thank you!
