### ISSUE TITLE
Notepad++ Plugins Admin

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [cpmcgrath/codealignment#83]
Please make the Code Alignment installable via Notepad++'s new Plugins Admin.

https://notepad-plus-plus.org/features/plugin-admin.html

**Comment by cpmcgrath** [comment]
Hi,
Code alignment has already been added to the Plugin Admin, unfortunately the list of plugins only gets refreshed with a new release. 
Code alignment was added well before the last release so I'm not sure why it hasn't made it into the release yet - I logged an issue about this at https://github.com/notepad-plus-plus/nppPluginList/issues/55
