### ISSUE TITLE
CodeAlignmentNpp.dll is not compatible with the current version of Notepad++

### ISSUE THREAD

**Issue by Unknown78** [cpmcgrath/codealignment#84]
I'm using Notepad++ v7.6.3 and it won't let me load the plugin and even suggest me to remove it.

**Comment by cpmcgrath** [comment]
Hi,
How did you install Code Alignment. Notepad++ recently completely changed where plugins are located and the structure they should follow.
Can you uninstall it and reinstalling it using the Plugin Admin and let me know if that fixes it?

**Comment by Unknown78** [comment]
Uninstall and Reinstalling `CodeAlignment` files from the plugins directory didn't fix it

Here is my step:
1. Download the plugin, here is the [direct link](https://github.com/cpmcgrath/codealignment/releases/download/v14.1/CodeAlignmentNpp_v14.1_x86.zip)
2. Extract it into `\Notepad++\plugins\` directory 
3. Open the Notepad++
4. From the Settings Menu Bar, Import the plugin `CodeAlignmentNpp.dll`

**Comment by FalcoGer** [comment]
CodeAlignment doesn't even show up in the 'Plugins Admin'. When installing via the Plugin Manager it doesn't appear in the Plugins menu at all.
Whether I dump the plugin manually into "C:\ProgramFiles\Notepad++\plugins" or "%appdata%\Notepad++\plugins" doesn't make a difference.
Using Notepad++ v7.6.3(64bit)

**Comment by cpmcgrath** [comment]
Last time I checked the Plugin Manager was installing to the old structure, so I doubt extensions installed using it will work anymore.

The Plugin Admin's list is a static list with each new version of Notepad++, so make sure you're on the latest version. The latest is currently 7.6.6

**Comment by chcg** [comment]
See also https://notepad-plus-plus.org/community/topic/17125/code-alignment-plugin-got-disabled-in-in-the-new-version-release

**Comment by cpmcgrath** [comment]
Thanks for that. I think the information in that link is enough for me to close this ticket

**Comment by lstudley** [comment]
Still an issue with  npp v8.3.3 and CodeAlignmentNpp_v14.1

**Comment by cpmcgrath** [comment]
This ticket has been closed for 3 years, if you're having an issue please log a new ticket with as much detail as you can provide.
The extension is working for me in Notepad++ 8.4.2
