### ISSUE TITLE
Align according to minimum number of spaces while reducing spacing as much as possible

### ISSUE THREAD

**Issue by pidgeon777** [cpmcgrath/codealignment#85]
Let's suppose I have a text like this one:

````
aasd-:
bbbbbb-:
c:
dssssssss:
eeee:
ffff----:
sss:
````

After alignment by `:` it would result:

````
aasd-----:
bbbbbb---:
c--------:
dssssssss:
eeee-----:
ffff-----:
sss------:
````

Colons are now aligned with spacing equal to `0` between the colon and the rightmost character of the longest word.

Now, let's suppose I remove some characters obtaining:

````
aasd-----:
bbbbbb---:
c--------:
dsssss:
eeee-----:
ffff-----:
sss------:
````

Realigning again I obtain:

````
aasd-----:
bbbbbb---:
c--------:
dsssss---:
eeee-----:
ffff-----:
sss------:
````

Colons are now aligned with spacing equal to `3` between the longest word and its rightmost character (`s` of `dsssss`).

What about reducing the further spacing so that the minimum spacing is still achieved?

I think that an option to automatically shorten the used spaces would be great so that after alignment I could automatically obtain the proper wanted minimum spacing. For example, by setting a minimum spacing of `0`, extra spacing would be reduced obtaining:

````
aasd--:
bbbbbb:
c-----:
dsssss:
eeee--:
ffff--:
sss---:
````

Moreover, by setting a "fixed" spacing of `2` characters for alignment, I could automatically align the code going from this:

````
aasd-:
bbbbbb-:
c:
dssssssss:
eeee:
ffff----:
sss:
````

or this:

````
aasd----------------:
bbbbbb----------------:
c---------------:
dssssssss---------------:
eeee---------------:
ffff-------------------:
sss---------------:
````

into this:

````
aasd-------:
bbbbbb-----:
c----------:
dssssssss--:
eeee-------:
ffff-------:
sss--------:
````

It would be great to let the user choose this "fixed" spacing amount: something which would reduce the spacing in excess so that the minimum wished spaced is reached, whilst maintaining the alignment.

**Comment by tomcap** [comment]
I was just about to suggest the same feature. This would make Code Alignment even more magical!

**Comment by cpmcgrath** [comment]
This is the same as #12
