### ISSUE TITLE
Align by comma add spaces to string with commas

### ISSUE THREAD

**Issue by kost-samsonov** [cpmcgrath/codealignment#87]
![devenv_2019-03-22_10-44-24](https://user-images.githubusercontent.com/48821773/54807814-7fd1c900-4c8f-11e9-8ac3-1529d6398673.png)

**Comment by kost-samsonov** [comment]
May be need add option "Ignore commas inside strings"

**Comment by cpmcgrath** [comment]
Hi,
I think this is outside of the scope for code alignment. Code Alignment is language agnostic, so it really doesn't - and I would argue shouldn't - understand what code is inside and string and what isn't.

**Comment by kost-samsonov** [comment]
Maybe you are right.
OK I solved this trouble by replacing comma with char "SINGLE LOW-9 QUOTATION MARK" [tyts](https://unicode-search.net/unicode-namesearch.pl?term=LOW%20SINGLE%20COMMA%20QUOTATION%20MARK&.submit=Search) in text and replace back after.
