### ISSUE TITLE
align by guidelines

### ISSUE THREAD

**Issue by ansayre** [cpmcgrath/codealignment#90]
it would be cool to be able to use the code alignment to align to guidelines e.g. align "/**<" to column 32 for doxygen comments

![image](https://user-images.githubusercontent.com/51709724/59278465-04e5d200-8c30-11e9-852c-3f4b7977c861.png)

**Comment by cpmcgrath** [comment]
I agree something like this would be cool, but I don't think it's in scope for this project.

As such I'll close this ticket. Thanks for the feedback
