### ISSUE TITLE
Align by space not working

### ISSUE THREAD

**Issue by JaredEStoddard** [cpmcgrath/codealignment#91]
Using the same scenario as #67, but indented by TABS, the _Align by Space_ does not work as expected.  I've reproduced this behavior both in Visual Studio 2019 and Notepad++.  My use case was attempting to line-up the TYPE portion of a CREATE TABLE command with >50 fields, e.g.,

CREATE TABLE MyTable (
\tTinyName VARCHAR(7) NOT NULL,
\tVeryLargeName DATE NOT NULL, ...

I tried both the built-in function and the custom "Align by" + space character.  Note that your suggestion of using "From Caret" _sometimes_ works as a stop-gap depending on the lines selected.

**Comment by cpmcgrath** [comment]
Sorry for the delay, can you provide more details? 
Code alignment treats tabs as spaces - if you try to align by \t it won't ever work.
As you mention align by space always uses the caret position to figure out which set of space you're wanting to use it on. So if for instance, your caret was on the Name part of TinyName it would align the types, if it was on the Name part of VeryLargeName, then it would try to align Date with Not.

**Comment by JaredEStoddard** [comment]
Chris,

 

I can’t really remember…  Consider it solved?

 

Thanks,

 

Jared
