### ISSUE TITLE
What about azure data studio?

### ISSUE THREAD

**Issue by mniak** [cpmcgrath/codealignment#92]
It would rock so much if you could publish this extension also to Azure Data Studio.

Link to documentation: https://docs.microsoft.com/en-us/sql/azure-data-studio/tutorial-create-extension?view=sql-server-2017

**Comment by mniak** [comment]
Oops, wrong repository.

**Comment by cpmcgrath** [comment]
You can actually use the Visual Studio Code port of Code Alignment on Azure Data Studio. 
https://github.com/cpmcgrath/codealignment-vscode 

At the moment you have to manually install the vsix file.
I'd love to make it available in the gallery for Azure Data Studio too, I've just been struggling to find time to work on anything with Code Alignment at the moment. But log a ticket under the other repository and I'll try my best to get around to it.

**Comment by mniak** [comment]
Thanks for your suggestion. I tried it and worked very well.
