### ISSUE TITLE
Example images for Before/After are missing

### ISSUE THREAD

**Issue by vortex852456** [cpmcgrath/codealignment#93]
see
https://github.com/cpmcgrath/codealignment/wiki/Example-1:-Align-by-equals https://github.com/cpmcgrath/codealignment/wiki/Example-2:-Align-by-string

**Comment by cpmcgrath** [comment]
Sorry for the delay. They should all be fixed now.
A small downside is some of the links will have changed. github names the files after the title, so the colon was stopping me from cloning the wiki locally.
