### ISSUE TITLE
Alignment only working for the first appearance 

### ISSUE THREAD

**Issue by pddzaic** [cpmcgrath/codealignment#95]
Let's assume the following text:

```
A|B|C
AB|CD|EF
ABC|DEF|GHI
```

When using "align by .." and choosing "|" than the code is formatted as follows:

```
A  |B|C
AB |CD|EF
ABC|DEF|GHI
```

But i think it should be:

```
A  |B  |C
AB |CD |EF
ABC|DEF|GHI
```

**Comment by cpmcgrath** [comment]
Hi,
The way to do this in Code Alignment is by Chaining alignments
https://github.com/cpmcgrath/codealignment/wiki/Chaining-Alignments

**Comment by pddzaic** [comment]
Thank ou very much for this information!
