### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by vinsworldcom** [cpmcgrath/codealignment#98]
I seen in:

codealignment/CodeAlignment.Npp/Main.cs:
```
        static void SetupIniFile()
        {
            var sbIniFilePath = new StringBuilder(Win32.MAX_PATH);
            Win32.SendMessage(PluginBase.nppData._nppHandle, NppMsg.NPPM_GETPLUGINSCONFIGDIR, Win32.MAX_PATH, sbIniFilePath);
            var path = sbIniFilePath.ToString();
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);

            s_iniFilePath = Path.Combine(path, PluginName + ".ini");
        }
```

Which is the proper way to get the config directory and save your plugin config. By this logic, there should exist:

$(NPP_INSTALL_DIR)/plugins/config/codealignment.ini

which I don’t have. Instead, I have:

$(USERPROFILE)/AppData/Local/Don_HO_don.h@free.fr/DefaultDomain_Path_<RANDOM_STRING>\7.86\user.config

`Grep`-ing your code does not turn up the Don_Ho* folder name.  Also a `strings` search doesn't find anything.  Why is your plugin storing configs there?

Windows 10 64-bit, N++ 7.8.6 64-bit.

Cheers.

**Comment by pryrt** [comment]
@cpmcgrath,

For more context, see [NPP Community: "Mystery Folder"](https://community.notepad-plus-plus.org/topic/19294/mystery-folder/), especially starting with [astrosofista's post](https://community.notepad-plus-plus.org/post/53248) and following

**Comment by cpmcgrath** [comment]
i think the config directory changed in notepad++ a few versions ago so I doubt it's meant to store the config file in the program folder anymore.

The code for integrating with Notepad++ relies on NppPlugin.DllExport.dll which is in the DllExport folder. 
I believe Don_HO_don.h@free.fr was the author of that.
